server:
  port: 2020
  
spring:  h2:    console:      enabled: true
      path: /h2-console
  datasource:    url: jdbc:h2:mem:testdb
  jpa:    show-sql: true
    hibernate:      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:    view:      prefix: /WEB-INF/jsps/
      suffix: .jsp
  ## Mail Properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: springboot18@gmail.com
    password: springboot@1859
    
# Other Mail Properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# TLS , port 587
          starttls:
            enable: true
          